### ISSUE TITLE
二维码是否有问题？

### ISSUE THREAD

**Issue by fenglinzeng** [useryangtao/vue-wechat#2]
二维码是不是有问题。
https://vue-wechat.github.io/#!/chat
或者
https://vue-wechat.github.io/
才能访问。
目前二维码好像指向https://vue-wechat.github.io/chat

**Comment by useryangtao** [comment]
感谢提醒，稍后改下。
因为最近将Vue-router配置hashbang属性改为true，导致路由加上了#!。没来得及改二维码。
