### ISSUE TITLE
是否有计划升级至vue 2.0呢？

### ISSUE THREAD

**Issue by Micjoyce** [useryangtao/vue-wechat#3]

**Comment by useryangtao** [comment]
已将《用vue2开发微信app界面》提到2017日程中。
开发完善的功能，如实现注册账号，加好友，实现聊天功能等等，
个人开发，精力有限，请各位持续关注。
主要初衷还是自己可以通过个人项目实践新技术，在业务中发现问题，积累经验。并且可以与各位交流发现不足。
